// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBppWS_Tvm6D7oWlb8u8YgPHjxAMUeeiIs',
    appId: '1:743892608847:web:0589e4da34171019b2c73a',
    messagingSenderId: '743892608847',
    projectId: 'skillswap-baskbear',
    authDomain: 'skillswap-baskbear.firebaseapp.com',
    storageBucket: 'skillswap-baskbear.firebasestorage.app',
    measurementId: 'G-ZZMM4TC9QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVjHxkRuH_Q33Vzmhxyv-B-0IsGnaJCLY',
    appId: '1:743892608847:android:9cefd55c940eb89bb2c73a',
    messagingSenderId: '743892608847',
    projectId: 'skillswap-baskbear',
    storageBucket: 'skillswap-baskbear.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyo3NsCJW_zM4Xqr60uOi_6ONUCN90iYU',
    appId: '1:743892608847:ios:a9c90f40099ee8c3b2c73a',
    messagingSenderId: '743892608847',
    projectId: 'skillswap-baskbear',
    storageBucket: 'skillswap-baskbear.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyo3NsCJW_zM4Xqr60uOi_6ONUCN90iYU',
    appId: '1:743892608847:ios:a9c90f40099ee8c3b2c73a',
    messagingSenderId: '743892608847',
    projectId: 'skillswap-baskbear',
    storageBucket: 'skillswap-baskbear.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBppWS_Tvm6D7oWlb8u8YgPHjxAMUeeiIs',
    appId: '1:743892608847:web:cdd2d2a730cac0fab2c73a',
    messagingSenderId: '743892608847',
    projectId: 'skillswap-baskbear',
    authDomain: 'skillswap-baskbear.firebaseapp.com',
    storageBucket: 'skillswap-baskbear.firebasestorage.app',
    measurementId: 'G-6TQ4T2TPWH',
  );
}
