name: skillswap
description: "A peer-to-peer skill sharing platform connecting learners with experts."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Services
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_database: ^11.3.7
  firebase_storage: ^12.4.7
  firebase_ui_auth: ^1.17.0
  firebase_ui_firestore: ^1.7.2

  # State Management
  provider: ^6.1.5
  flutter_riverpod: ^2.6.1

  # UI & Animation
  flutter_svg: ^2.0.10+1
  lottie: ^3.3.1
  shimmer: ^3.0.0
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  flutter_staggered_grid_view: ^0.7.0

  # Forms & Input
  image_picker: ^1.0.4
  file_picker: ^10.1.9
  intl: ^0.20.2
  url_launcher: ^6.3.1

  # Utilities
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  flutter_dotenv: ^5.2.1

  # New Features
  flutter_rating_bar: ^4.0.1  # For review system
  share_plus: ^7.2.2          # For social sharing
           # For deep links

  # Icons
  cupertino_icons: ^1.0.5
  line_icons: ^2.0.3
  material_design_icons_flutter: ^7.0.7296
  table_calendar: ^3.2.0
  flutter_stripe: ^11.5.0
  http: ^1.1.2
  cloud_functions: ^5.5.2

  # New Features
  fl_chart: ^0.64.0

  # New Features
  tuple: ^2.0.0

  # Google Fonts
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.6
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
